-- Developer logs for debugging and operational notes (admin UI under Dev → Logs).

create table if not exists public.app_dev_logs (
  id bigint generated by default as identity primary key,
  level text not null check (level in ('debug', 'info', 'warn', 'error')),
  message text not null,
  source text,
  context jsonb,
  created_by_email text,
  created_at timestamptz not null default now()
);

create index if not exists app_dev_logs_created_at_idx on public.app_dev_logs (created_at desc);

alter table public.app_dev_logs enable row level security;

-- No policies: anon/authenticated cannot access; service role bypasses RLS.
