-- Per-calendar-month target overrides on top of `nmac_master_targets` (run once if not in schema.sql).

create table if not exists public.nmac_master_target_months (
  id bigint generated by default as identity primary key,
  year int not null,
  month_index int not null check (month_index >= 0 and month_index <= 11),
  values jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  unique (year, month_index)
);

alter table public.nmac_master_target_months enable row level security;

drop policy if exists "nmac_master_target_months_read" on public.nmac_master_target_months;
create policy "nmac_master_target_months_read"
on public.nmac_master_target_months
for select
using (true);

drop policy if exists "nmac_master_target_months_write" on public.nmac_master_target_months;
create policy "nmac_master_target_months_write"
on public.nmac_master_target_months
for all
using (true)
with check (true);
