-- Add-on for projects that already ran schema.sql before NMAC monthly storage existed.
-- Safe to run once in Supabase SQL Editor.

create table if not exists public.nmac_master_monthly (
  id bigint generated by default as identity primary key,
  year int not null,
  month_index int not null check (month_index >= 0 and month_index <= 11),
  values jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  unique (year, month_index)
);

alter table public.nmac_master_monthly enable row level security;

drop policy if exists "nmac_master_monthly_read" on public.nmac_master_monthly;
create policy "nmac_master_monthly_read"
on public.nmac_master_monthly
for select
using (true);

drop policy if exists "nmac_master_monthly_write" on public.nmac_master_monthly;
create policy "nmac_master_monthly_write"
on public.nmac_master_monthly
for all
using (true)
with check (true);
