-- Run in Supabase SQL Editor. Re-run safe: policies are dropped first.

create table if not exists public.kpi_definitions (
  id bigint generated by default as identity primary key,
  slug text unique not null,
  label text not null,
  unit text not null check (unit in ('count', 'percent', 'minutes', 'score')),
  suffix text not null default '',
  target numeric not null,
  sort_order int not null
);

create table if not exists public.kpi_weekly_values (
  id bigint generated by default as identity primary key,
  kpi_slug text not null references public.kpi_definitions(slug) on delete cascade,
  year int not null,
  week_index int not null,
  this_year numeric,
  last_year numeric,
  unique (kpi_slug, year, week_index)
);

alter table public.kpi_definitions enable row level security;
alter table public.kpi_weekly_values enable row level security;

-- PostgreSQL does not support "CREATE POLICY IF NOT EXISTS". Drop then create.
-- No TO clause: policy applies to all roles (including anon), so the browser anon key works.

drop policy if exists "kpi_definitions_read" on public.kpi_definitions;
create policy "kpi_definitions_read"
on public.kpi_definitions
for select
using (true);

drop policy if exists "kpi_weekly_values_read" on public.kpi_weekly_values;
create policy "kpi_weekly_values_read"
on public.kpi_weekly_values
for select
using (true);

-- Temporary: allow inserts/updates from the app. Tighten when Auth + roles exist.
drop policy if exists "kpi_weekly_values_write" on public.kpi_weekly_values;
create policy "kpi_weekly_values_write"
on public.kpi_weekly_values
for all
using (true)
with check (true);

-- App users & OTP (server-side only via service role; no RLS policies for anon)
create table if not exists public.app_users (
  id uuid primary key default gen_random_uuid(),
  email text unique not null,
  first_name text,
  last_name text,
  role text not null check (role in ('viewer', 'editor', 'admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.auth_otp_codes (
  email text primary key,
  code_hash text not null,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);

alter table public.app_users enable row level security;
alter table public.auth_otp_codes enable row level security;

-- No policies: anon/authenticated cannot access; service role bypasses RLS.
