import { createServiceRoleClient } from "@/lib/supabase/admin";

export const DEV_LOG_LEVELS = ["debug", "info", "warn", "error"] as const;
export type DevLogLevel = (typeof DEV_LOG_LEVELS)[number];

export const DEV_LOGS_SETUP_SQL = `-- Run in Supabase SQL Editor
create table if not exists public.app_dev_logs (
  id bigint generated by default as identity primary key,
  level text not null check (level in ('debug', 'info', 'warn', 'error')),
  message text not null,
  source text,
  context jsonb,
  created_by_email text,
  created_at timestamptz not null default now()
);

create index if not exists app_dev_logs_created_at_idx on public.app_dev_logs (created_at desc);

alter table public.app_dev_logs enable row level security;`;

export type DevLogEntry = {
  id: number;
  level: DevLogLevel;
  message: string;
  source: string | null;
  context: Record<string, unknown> | null;
  created_by_email: string | null;
  created_at: string;
};

type DevLogRow = {
  id: number;
  level: DevLogLevel;
  message: string;
  source: string | null;
  context: Record<string, unknown> | null;
  created_by_email: string | null;
  created_at: string;
};

export type DevLogsListResult = {
  logs: DevLogEntry[];
  setupRequired?: boolean;
  error?: string;
};

function rowToEntry(row: DevLogRow): DevLogEntry {
  return {
    id: row.id,
    level: row.level,
    message: row.message,
    source: row.source,
    context: row.context,
    created_by_email: row.created_by_email,
    created_at: row.created_at,
  };
}

function isMissingDevLogsTable(message: string): boolean {
  const m = message.toLowerCase();
  return (
    m.includes("app_dev_logs") &&
    (m.includes("does not exist") ||
      m.includes("schema cache") ||
      m.includes("could not find") ||
      m.includes("relation"))
  );
}

export function isDevLogLevel(value: unknown): value is DevLogLevel {
  return typeof value === "string" && (DEV_LOG_LEVELS as readonly string[]).includes(value);
}

export type AppendDevLogInput = {
  level: DevLogLevel;
  message: string;
  source?: string | null;
  context?: Record<string, unknown> | null;
  createdByEmail?: string | null;
};

export type AppendDevLogResult = {
  log: DevLogEntry | null;
  setupRequired?: boolean;
  error?: string;
};

export async function appendDevLog(input: AppendDevLogInput): Promise<AppendDevLogResult> {
  const message = input.message.trim();
  if (!message) return { log: null, error: "Message is required." };

  try {
    const supabase = createServiceRoleClient();
    const { data, error } = await supabase
      .from("app_dev_logs")
      .insert({
        level: input.level,
        message,
        source: input.source?.trim() || null,
        context: input.context ?? null,
        created_by_email: input.createdByEmail?.trim().toLowerCase() || null,
      })
      .select("id,level,message,source,context,created_by_email,created_at")
      .single();

    if (error) {
      console.error("[dev-log]", error);
      if (isMissingDevLogsTable(error.message)) {
        return { log: null, setupRequired: true, error: "Dev logs table is missing in Supabase." };
      }
      return { log: null, error: error.message };
    }

    if (!data) return { log: null, error: "Could not save log." };
    return { log: rowToEntry(data as DevLogRow) };
  } catch (err) {
    console.error("[dev-log]", err);
    return { log: null, error: err instanceof Error ? err.message : "Could not save log." };
  }
}

export async function listDevLogs(limit = 100): Promise<DevLogsListResult> {
  try {
    const supabase = createServiceRoleClient();
    const { data, error } = await supabase
      .from("app_dev_logs")
      .select("id,level,message,source,context,created_by_email,created_at")
      .order("created_at", { ascending: false })
      .limit(Math.min(Math.max(limit, 1), 500));

    if (error) {
      console.error("[dev-log]", error);
      if (isMissingDevLogsTable(error.message)) {
        return { logs: [], setupRequired: true, error: "Dev logs table is missing in Supabase." };
      }
      return { logs: [], error: error.message };
    }

    return { logs: ((data ?? []) as DevLogRow[]).map(rowToEntry) };
  } catch (err) {
    console.error("[dev-log]", err);
    return {
      logs: [],
      error: err instanceof Error ? err.message : "Could not load logs.",
    };
  }
}

export async function clearDevLogs(): Promise<{ ok: boolean; setupRequired?: boolean; error?: string }> {
  try {
    const supabase = createServiceRoleClient();
    const { error } = await supabase.from("app_dev_logs").delete().neq("id", 0);
    if (error) {
      console.error("[dev-log]", error);
      if (isMissingDevLogsTable(error.message)) {
        return { ok: false, setupRequired: true, error: "Dev logs table is missing in Supabase." };
      }
      return { ok: false, error: error.message };
    }
    return { ok: true };
  } catch (err) {
    console.error("[dev-log]", err);
    return { ok: false, error: err instanceof Error ? err.message : "Could not clear logs." };
  }
}
